# Generated by Django 5.1.3 on 2024-12-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='493E5', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
