# Generated by Django 5.1.3 on 2024-12-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerch', '0004_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='B1B79', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
