# Generated by Django 5.1.3 on 2024-12-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerch', '0009_product_tags_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='B886F', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
