# Generated by Django 5.1.3 on 2024-12-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerch', '0010_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='E7A1A', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
