# Generated by Django 5.1.3 on 2024-12-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerch', '0012_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='E012B', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
