# Generated by Django 5.1.3 on 2024-12-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='housenumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
