# Generated by Django 5.1.3 on 2024-12-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='assets/img/slider/3.png', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('Delivery', models.CharField(choices=[('free', 'Free Delivery'), ('standard', 'Standard Delivery'), ('qualified', 'Qualified Delivery')], default='standard', max_length=500)),
                ('category', models.CharField(choices=[('dress', 'Baby Dress'), ('toy', 'Baby Toys')], default='dress', max_length=500)),
            ],
        ),
    ]
