# Generated by Django 5.1.3 on 2024-11-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_images',
            name='image',
            field=models.ImageField(default='assets/img/slider/3.png', upload_to='images/'),
        ),
    ]
