# Generated by Django 5.1.3 on 2024-11-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_offer_images_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='offer_images',
            new_name='OfferImage',
        ),
    ]
