# Generated by Django 5.1.3 on 2025-01-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_user_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pointmessage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
