# Generated by Django 5.1.3 on 2025-01-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='reply',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='reply',
        ),
    ]
