# Generated by Django 5.1.3 on 2025-01-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_comments_reply_delete_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='reply',
            field=models.TextField(blank=True, default='Thank you for your comment. We will get back to you soon.', max_length=1000, null=True),
        ),
    ]
